# $HOME/.config/tmuxinator/stock-research.yml

name: stock-research
root: ~/Projects/stock-research/

windows:
  - repl:
      - source venv/bin/activate
      - clear
  - sql:
      layout: even-horizontal
      panes:
        - one:
            - source venv/bin/activate
            - clear
            - db/console
        - two:
            - source venv/bin/activate
            - clear
            - db/console
  - console:
      - source venv/bin/activate
      - clear
