# $HOME/.config/tmuxinator/stock-research.yml

name: stock-research
root: ~/Projects/stock-research/

windows:
  - repl:
      - source venv/bin/activate
      - clear
      - ipython
  - sql:
      - source venv/bin/activate
      - clear
      - bin/dbconsole
  - console:
      - source venv/bin/activate
      - clear
  - web:
      - source venv/bin/activate
      - clear
      - python -m research.web.app
